var ob_util={copyright:"Copyright (c) 2015 by SAS Institute Inc., Cary, NC, USA. All Rights Reserved.",webmarketing:!1,newvid:!1,newsid:!1,oldsid:null,lastActivity:0,lastInactivePeriod:0,csn:0,logging:!1,ccsProtocol:null,FS:"/",f:"function",clickEvents:[],addClickEvent:function(a){this.clickEvents[this.clickEvents.length]=a},sendClickEvents:function(a){for(var b=0;b<this.clickEvents.length;b++)this.clickEvents[b].send(a);this.clickEvents=[]},checkClickEvents:function(){this.sendClickEvents();setTimeout(function(){ob_util.checkClickEvents()},
2E3)},log:function(a){this.logging&&("undefined"===typeof console||"undefined"===typeof console.log||console.log(a))},toLowerCase:function(a){return a.toLowerCase()},nsn:function(){return++this.csn},ckR:function(a){var b=a+"=";a=document.cookie;var c=a.indexOf(b);return-1!=c?(b=c+b.length,c=a.indexOf(";",b),-1==c&&(c=a.length),a.substring(b,c)):null},ckW:function(a,b,c,e,f){e=null==e||0==e.length?"":"; domain="+e;document.cookie=a+"="+b+"; expires="+(new Date(f)).toGMTString()+"; path="+c+e},sckW:function(a,
b,c,e,f){null==c&&(c="/");null==f&&(f=0);document.cookie=a+"="+(b+"."+f)+"; path="+c+(null==e||0==e.length?"":"; domain="+e)},getURIExtension:function(a){a=new String(a.split("?")[0]);return a.substr(a.lastIndexOf(".")+1)},isScriptLink:function(a,b){b=ob_util.toLowerCase(a.toString());return 0==b.indexOf("javascript:")||0==b.indexOf("vbscript:")},location:function(){var a=new String(location.protocol);return a.substr(0,a.length-1)},host:function(){return new String(location.host)},strEndsWith:function(a,
b){return-1!=a.indexOf(b,a.length-b.length)},strStartsWith:function(a,b){return a.slice(0,b.length)==b},strContains:function(a,b){return-1!=a.indexOf(b)},strEquals:function(a,b){return a==b},strOp:function(a,b,c){if("equals"!=a){if("contains"==a)return ob_util.strContains(b,c);if("startsWith"==a||"endsWith"==a)return ob_util.strStartsWith(b,c);if("regex"==a)return(a=RegExp(c).exec(b))&&0<a.length}return ob_util.strEquals(b,c)},flash:function(a,b,c,e,f,g){a={e:!1,v:""};if((c=navigator.plugins)&&c.length)if((f=
c["Shockwave Flash"])||(f=c["Shockwave Flash 2.0"]),f&&(a.e=!0,g=f.description))a.v=g.substr(g.indexOf("Flash")+6);if("Microsoft Internet Explorer"==navigator.appName)for(b=15;0<b;b--)try{e=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+b);a.e=!0;a.v=e.GetVariable("$version");break}catch(k){}return a},svg:function(a,b,c,e,f,g){a={e:!1,v:""};c=navigator.mimeTypes;for(b=0;b<c.length;b++)t=new String(c[b].type),0==t.indexOf("image/svg+xml")&&(a.e=!0,e=t.split("sion=")[1],e>a.v&&(a.v=e));"Microsoft Internet Explorer"==
navigator.appName&&(e=new ActiveXObject("Adobe.SVGCtl"),a.e=!0,a.v=e.GetVariable("$version"));return a},flashdirector:function(a,b,c,e,f,g){a={e:!1,v:""};c=navigator.mimeTypes;for(b=0;b<c.length;b++)t=new String(c[b].type),0==t.indexOf("application/x-director")&&(a.e=!0,f=t.split("sion=")[1],f>a.v&&(a.v=f));if("Microsoft Internet Explorer"==navigator.appName)for(b=15;0<b;b--)try{e=new ActiveXObject("SWCtl.SWCtl."+b);a.e=!0;a.v=e.GetVariable("$version");break}catch(k){}return a},realplayer:function(a,
b,c,e,f,g){a={e:!1,v:""};c=navigator.mimeTypes;for(b=0;b<c.length;b++)t=new String(c[b].type),0==t.indexOf("audio/x-pn-realaudio-plugin")&&(a.e=!0,f=t.split("sion=")[1],f>a.v&&(a.v=f));if("Microsoft Internet Explorer"==navigator.appName)for(b=15;0<b;b--)try{e=new ActiveXObject("rmocx.RealPlayer G2 Control."+b);a.e=!0;a.v=e.GetVariable("$version");break}catch(k){}return a},quicktime:function(a,b,c,e,f,g){a={e:!1,v:""};c=navigator.mimeTypes;for(b=0;b<c.length;b++)t=new String(c[b].type),0==t.indexOf("video/quicktime")&&
(a.e=!0,f=t.split("sion=")[1],f>a.v&&(a.v=f));if("Microsoft Internet Explorer"==navigator.appName)for(b=15;0<b;b--)try{e=new ActiveXObject("QuickTimeCheckObject.QuickTimeCheck."+b);a.e=!0;a.v=e.GetVariable("$version");break}catch(k){}return a},mediaplayer:function(a,b,c,e,f,g){a={e:!1,v:""};c=navigator.mimeTypes;for(b=0;b<c.length;b++)t=new String(c[b].type),0==t.indexOf("application/x-mplayer2")&&(a.e=!0,tv=t.split("sion=")[1],tv>a.v&&(a.v=tv));if("Microsoft Internet Explorer"==navigator.appName)for(b=
15;0<b;b--)try{e=new ActiveXObject("MediaPlayer.MediaPlayer."+b);a.e=!0;a.v=e.GetVariable("$version");break}catch(k){}return a},acrobat:function(a,b,c,e,f,g){a={e:!1,v:""};c=navigator.mimeTypes;for(b=0;b<c.length;b++)t=new String(c[b].type),0==t.indexOf("application/pdf")&&(a.e=!0,f=t.split("sion=")[1],f>a.v&&(a.v=f));if("Microsoft Internet Explorer"==navigator.appName)for(b=15;0<b;b--)try{e=new ActiveXObject("PDF.PdfCtrl."+b);a.e=!0;a.v=e.GetVariable("$version");break}catch(k){}return a},brightcove:function(a,
b,c,e,f,g,k,p,r){a={e:!1,v:""};b=document.getElementsByTagName("script");if(!isUndefined(b))for(;0<b.length;){-1!=b[0].indexOf("brightcove")&&(a.e=!0);break}return a},java:function(a,b,c,e,f,g,k,p,r){a={e:!1,v:""};if("Microsoft Internet Explorer"==navigator.appName){c=2;a:for(;0<c;c--)for(f=9;0<=f;f--)for(g=5;0<=g;g--){d=c+"."+f+"."+g;try{new ActiveXObject("JavaWebStart.isInstalled."+d+".0");a.e=!0;a.v=d;break a}catch(s){}}}else{c=navigator.mimeTypes;for(b=0;b<c.length;b++)p=new String(c[b].type),
0==p.indexOf("application/x-java-applet")&&(a.e=!0,r=p.split("sion=")[1],r>a.v&&(a.v=r))}if(""!=a.v)return a;a.e=navigator.javaEnabled();a.v=a.e&&"undefined"!=typeof java?java.lang.System.getProperty("java.version"):"";return a},isUndefined:function(a){return"undefined"==typeof a?!0:!1},idOf:function(a){return""!=a.id?a.id:a.name},formTag:function(a,b){for(b=ob_util.toLowerCase(b);null!=a&&ob_util.toLowerCase(a.tagName)!=b&&"body"!=ob_util.toLowerCase(a.tagName);)a=a.parentNode;if(null==a||ob_util.toLowerCase(a.tagName)!=
b||ob_util.isScriptLink(a))a=null;return a},parseUri:function(a){var b=document.createElement("a");b.href=a;return{protocol:b.protocol.replace(":",""),host:b.hostname,port:b.port,path:b.pathname,search:b.search.substring(1)}},localUri:function(){return this.parseUri(window.location.href)},isDescendant:function(a,b){for(var c=b.parentNode;null!=c;){if(c==a)return!0;c=c.parentNode}return!1},isArray:function(a){return a&&"[object Array]"===Object.prototype.toString.call(a)},getElementPath:function(a){var b=
null!=a.id&&!ob_util.isUndefined(a.id)&&""!=a.id?a.id:a.nodeName;for(a=a.parentNode;null!=(a=a.parentNode);)b=!ob_util.isUndefined(a.id)&&null!=a.id&&""!=a.id?a.id+"/"+b:a.nodeName+"/"+b;return"//"+b},getElementSelector:function(a){if(null==a)return"";var b=a.tagName.toLowerCase();if("body"!=b&&"html"!=b){var c=a.getAttribute("id"),e=a.getAttribute("class");a=a.getAttribute("name");if(c)b=0<=c.indexOf(".")?b+("[id='"+c+"']"):b+("#"+c);else{if(e){c=e.split(/\s+/);for(e=0;e<c.length;e++)b+="."+c[e].trim()}a&&
(b+="[name='"+a+"']")}}return b},getElementFullSelector:function(a){for(var b=ob_util.getElementSelector(a);null!=(a=a.parentElement);)b=ob_util.getElementSelector(a)+" > "+b;return b},getElementInnerText:function(a){return a.textContent&&"undefined"!=typeof a.textContent?a.textContent:a.innerText},isIE8Browser:function(){var a=-1,b=navigator.userAgent,c=/Trident\/([0-9]{1,}[.0-9]{0,})/;null!=c.exec(b)&&(a=parseFloat(RegExp.$1));if(4==a)return!0;c=/MSIE ([0-9]{1,}[.0-9]{0,})/;return null!=c.exec(b)&&
(a=parseFloat(RegExp.$1),9>a&&0<a)?!0:!1},isFirefoxBrowser:function(){return"undefined"!==typeof InstallTrigger},isSafariBrowser:function(){return 0<Object.prototype.toString.call(window.HTMLElement).indexOf("Constructor")},pause:function(a){for(var b=(new Date).getTime();(new Date).getTime()-b<a;);},MD5:null,Sizzle:null};
function ob_form(a,b){this.attempts=0;this.changes={};for(var c=0;c<a.length;c++){var e=a.elements[c];if("password"!=ob_util.toLowerCase(e.type)){var f=ob_util.idOf(e);if(""==f)ob_util.log("un-id'd element in form ["+a.id+"] skipped");else{var g=ob_util.toLowerCase(e.tagName),e=ob_util.toLowerCase(e.type);ob_util.log("tracking changes on "+b+"["+g+":"+e+"]:"+f);this.changes[f]=0}}}}
function _ob_configure(){this.w3c="undefined"==typeof window.event?!0:!1;this.w3c||(this.w3c="undefined"==typeof document.createEventObject?!0:!1);this.limIE=2083;this.validateEvents=!0;this.sendMeta={};this.sendCookies={};this.sendJsvars={};this.sendMeta.load=!0;this.sendMeta.cart=!0;this.sendCookies.load=!0;this.sendCookies.cart=!0;this.sendJsvars.load=!0;this.sendJsvars.cart=!0;this.forms={}}
_ob_configure.prototype.initialize=function(){typeof this.ob_cfg==ob_util.f?(this.ob_cfg(),_ob_dom.initialize()):ob_util.log("ERROR: _ob_configure.initialize(): No configuration.")};_ob_configure.prototype.getLoadId=function(){return this.load_guid};_ob_configure.prototype.getDomain=function(){return document.domain};
var ob_configure=new _ob_configure,_ob_dom=function(){var a=function(a,b,e,c){if("object"!=typeof a||(ob_util.isUndefined(b)||""==b)||typeof e!=ob_util.f)return!1;ob_util.isUndefined(c)&&(c=!0);ob_util.isUndefined(window.event)?a.addEventListener(b,e,c):a.attachEvent("on"+b,e);return!0},b=function(a){if(ob_util.isUndefined(ob_configure.isCollectionEnabled().pageloads)||"true"==ob_configure.isCollectionEnabled().pageloads){var b=new ob_event("load");setTimeout(function(){b.send()},0);ob_util.isFirefoxBrowser()&&
setTimeout(function(){ob_util.checkClickEvents()},2E3)}(new ob_injector).injectAll();_ob_cart_handlers.scrapeHandler()},c=function(a){(ob_util.isUndefined(ob_configure.isCollectionEnabled().pageloads)||"true"==ob_configure.isCollectionEnabled().pageloads)&&(new ob_event("unload")).send(!1)},e=function(a){if(ob_util.isUndefined(ob_configure.isCollectionEnabled().pageloads)||"true"==ob_configure.isCollectionEnabled().pageloads){var b=new ob_event("DOMContentLoaded");setTimeout(function(){b.send()},
0)}},f=function(a){if(ob_util.isUndefined(ob_configure.isCollectionEnabled().clicks)||"true"==ob_configure.isCollectionEnabled().clicks)ob_configure.w3c?a.addEventListener("click",z,!0):a.attachEvent("onclick",z);"true"==ob_configure.isCollectionEnabled().mouseovers&&(ob_configure.w3c?a.addEventListener("mouseover",z,!0):a.attachEvent("onmouseover",z))},g=function(a,b,e){for(var c={},f,h,g=0;g<a.length;g++){var l=a[g];f=!0;if(null!=l){var q=l.uri;if(void 0!=q){for(var m=0;m<q.length;m++){var n=q[m].p.op,
v=q[m].p.values;h=!1;for(var k=0;k<v.length;k++){var p=q[m].p.values[k],r=ob_util.parseUri(window.location.href).path;if(ob_util.strOp(n,r,p)){h=!0;break}}if(!h){f=!1;break}}if(!f)continue}m=l.protocol;if(void 0!=m){n=m.p.op;v=m.p.values;h=!1;for(k=0;k<v.length;k++)if(p=m.p.values[k],q=ob_util.location(),ob_util.strOp(n,q,p)){h=!0;break}if(!h)continue}m=l.domain;if(void 0!=m&&(n=m.p.op,"all"!=n&&(v=m.p.values,0<v.length))){q=ob_util.host();h=!1;for(k=0;k<v.length;k++)if(p=m.p.values[k],ob_util.strOp(n,
q,p)){h=!0;break}if(!h)continue}r=l.form;if(void 0!=r){for(m=0;m<r.length;m++){q=r[m].attr;n=r[m].op;v=r[m].values;h=!1;for(k=0;k<v.length;k++){var p=r[m].values[k],s=b;"name"==q&&(s=e);if(ob_util.strOp(n,s,p)){h=!0;break}}if(!h){f=!1;break}}if(!f)continue}f=l.field;if(void 0!=f)for(m=0;m<f.length;m++){q=f[m].attr;v=f[m].values;for(k=0;k<v.length;k++)p=f[m].values[k],c[p+"_"+q]=p}}}return c},k=function(a,b){var e=ob_util.idOf(a);if(null==e||""==e)e="anonymous_form_"+ ++b;ob_configure.forms[e]=new ob_form(a,
e);var c=_ob_configure.prototype.getFormConfig();ob_configure.forms[e].obs=g(c.obs,a.id,a.name);ob_configure.forms[e].ign=g(c.ign,a.id,a.name);for(c=0;c<a.length;c++){var f=a.elements[c],h=ob_util.toLowerCase(f.tagName),l=ob_util.toLowerCase(f.type);("input"==h||"button"==h)&&"submit"==l?p(f,e):"input"==h&&("text"==l||"textarea"==l||"color"==l||"date"==l||"datetime"==l||"datetime-local"==l||"email"==l||"file"==l||"month"==l||"number"==l||"range"==l||"search"==l||"tel"==l||"time"==l||"url"==l||"week"==
l)?r(f,e):"select"==h?s(f,e):"input"==h&&"checkbox"==l?x(f,e):"input"==h&&"radio"==l&&(h=e,(ob_util.isUndefined(ob_configure.isCollectionEnabled().fieldinteractions)||"true"==ob_configure.isCollectionEnabled().fieldinteractions)&&x(f,h))}c=a.getElementsByTagName("label");if(!ob_util.isUndefined(c))for(f=0;f<c.length;f++)u(c[f],e)},p=function(a,b){if(ob_util.isUndefined(ob_configure.isCollectionEnabled().formsubmits)||"true"==ob_configure.isCollectionEnabled().formsubmits)ob_configure.w3c?(a.addEventListener("click",
function(){return function(a){A(a,b)}}(),!0),a.addEventListener("focus",function(){return function(a){w(a,b)}}(),!0)):(a.attachEvent("onclick",function(){return function(a){A(a,b)}}(),!0),a.attachEvent("onfocus",function(){return function(a){w(a,b)}}(),!0));"true"==ob_configure.isCollectionEnabled().mouseovers&&(ob_configure.w3c?a.addEventListener("mouseover",function(){return function(a){A(a,b)}}(),!0):a.attachEvent("onmouseover",function(){return function(a){A(a,b)}}()))},r=function(a,b){if(ob_util.isUndefined(ob_configure.isCollectionEnabled().fieldinteractions)||
"true"==ob_configure.isCollectionEnabled().fieldinteractions)ob_configure.w3c?(a.addEventListener("blur",function(){return function(a){w(a,b)}}()),a.addEventListener("focus",function(){return function(a){w(a,b)}}()),a.addEventListener("change",function(){return function(a){w(a,b)}}(),!0),("text"==a.getAttribute("type")||"textarea"==a.getAttribute("type"))&&a.addEventListener("select",function(){return function(a){w(a,b)}}(),!0)):(a.attachEvent("onblur",function(){return function(a){w(a,b)}}()),a.attachEvent("onfocus",
function(){return function(a){w(a,b)}}()),a.attachEvent("onchange",function(){return function(a){w(a,b)}}(),!0),("text"==a.getAttribute("type")||"textarea"==a.getAttribute("type"))&&a.attachEvent("onselect",function(){return function(a){w(a,b)}}(),!0));"true"==ob_configure.isCollectionEnabled().mouseovers&&(ob_configure.w3c?a.addEventListener("mouseover",function(){return function(a){w(a,b)}}(),!0):a.attachEvent("onmouseover",function(){return function(a){w(a,b)}}()))},s=function(a,b){if(ob_util.isUndefined(ob_configure.isCollectionEnabled().fieldinteractions)||
"true"==ob_configure.isCollectionEnabled().fieldinteractions)ob_configure.w3c?(a.addEventListener("change",function(){return function(a){w(a,b)}}(),!0),a.addEventListener("focus",function(){return function(a){w(a,b)}}(),!0)):(a.attachEvent("onfocus",function(){return function(a){w(a,b)}}(),!0),a.attachEvent("onchange",function(){return function(a){w(a,b)}}(),!0));"true"==ob_configure.isCollectionEnabled().mouseovers&&(ob_configure.w3c?a.addEventListener("mouseover",function(){return function(a){w(a,
b)}}(),!0):a.attachEvent("onmouseover",function(){return function(a){w(a,b)}}()))},x=function(a,b){if(ob_util.isUndefined(ob_configure.isCollectionEnabled().fieldinteractions)||"true"==ob_configure.isCollectionEnabled().fieldinteractions)ob_configure.w3c?(a.addEventListener("blur",function(){return function(a){w(a,b)}}(),!0),a.addEventListener("change",function(){return function(a){w(a,b)}}(),!0),a.addEventListener("focus",function(){return function(a){w(a,b)}}(),!0)):(a.attachEvent("onblur",function(){return function(a){w(a,
b)}}(),!0),a.attachEvent("onfocus",function(){return function(a){w(a,b)}}(),!0),a.attachEvent("onchange",function(){return function(a){w(a,b)}}(),!0));"true"==ob_configure.isCollectionEnabled().mouseovers&&(ob_configure.w3c?a.addEventListener("mouseover",function(){return function(a){w(a,b)}}(),!0):a.attachEvent("onmouseover",function(){return function(a){w(a,b)}}()))},u=function(a,b){ob_configure.w3c?void 0!=a&&a.addEventListener("focus",function(){return function(a){w(a,b)}}(),!0):void 0!=a&&a.attachEvent("onfocus",
function(){return function(a){w(a,b)}}(),!0);"true"==ob_configure.isCollectionEnabled().mouseovers&&(ob_configure.w3c?void 0!=a&&a.addEventListener("mouseover",function(){return function(a){w(a,b)}}(),!0):void 0!=a&&a.attachEvent("onmouseover",function(){return function(a){w(a,b)}}()))},v=function(){if(ob_util.isUndefined(ob_configure.isCollectionEnabled().contentevents)||"true"==ob_configure.isCollectionEnabled().contentevents){var a,b;"undefined"!==typeof document.hidden?(a="hidden",b="visibilitychange"):
"undefined"!==typeof document.mozHidden?(a="mozHidden",b="mozvisibilitychange"):"undefined"!==typeof document.msHidden?(a="msHidden",b="msvisibilitychange"):"undefined"!==typeof document.webkitHidden&&(a="webkitHidden",b="webkitvisibilitychange");"undefined"!==typeof a&&"undefined"!==typeof document.addEventListener&&document.addEventListener(b,function(){return function(b){B(b,document[a])}}(),!0)}},q=function(){if(ob_util.isUndefined(ob_configure.isCollectionEnabled().contentevents)||"true"==ob_configure.isCollectionEnabled().contentevents){var a=
window.MutationObserver||window.WebKitMutationObserver||window.MozMutationObserver,b=(new _ob_contentvisible_configuration).getConfig();if(b)for(var e in b)try{for(var c=b[e],f=ob_util.Sizzle(c),h=0;h<f.length;h++)a?(new a(function(){var a=e,b=c;return function(e){C(e,a,b)}}())).observe(f[h],{childList:!0,subtree:!0,attributes:!0,attributeOldValue:!0,characterData:!0,characterDataOldValue:!0}):f[h].addEventListener&&(f[h].addEventListener("DOMNodeInserted",function(){return function(a){D(a,e,c)}}(),
!0),f[h].addEventListener("DOMAttrModified",function(){return function(a){E(a,e,c)}}(),!0),f[h].addEventListener("DOMNodeRemoved",function(){return function(a){F(a,e,c)}}(),!0),f[h].addEventListener("DOMCharacterDataModified",function(){return function(a){G(a,e,c)}}(),!0))}catch(l){ob_util.log("exception occurred in instrumentContentVisibility: "+l)}}},h=function(a,b,e){var c=function(){return function(e,c,f,h){H(a,b,e,c,f,h)}}();_ob_jsvar.watch(e,c)},l=function(a){n(a.target)},n=function(a){var b;
if(void 0!=a.href)f(a);else for(b=0;b<document.forms.length;b++)if(document.forms[b]==a){k(a);break}if(a.hasChildNodes())for(b=0;b<a.childNodes.length;b++)n(a.childNodes.item(b))},m=function(a){var b=ob_util.isUndefined(a.type)?ob_util.toLowerCase(a.nodeName):ob_util.toLowerCase(a.type),e=ob_util.idOf(a),c=a.value;if("label"==b)ob_util.isUndefined(e)&&ob_util.isUndefined(a.htmlFor),c=a.textContent;else if("checkbox"==b&&!a.checked)c="";else if("select-multiple"==b){c="";for(b=0;b<a.selectedOptions.length;b++)e=
a.selectedOptions[b],0<c.length&&(c+=","),c+=e.value}return c},A=function(a,b){a||(a=window.event);var e=ob_util.toLowerCase(a.type),c=ob_configure.w3c?a.target:a.srcElement,f=ob_util.formTag(c,"form"),h=b;ob_util.isUndefined(h)&&(h=ob_util.idOf(f));"click"==e&&(e="submit");var l=ob_configure.forms[h];ob_util.isUndefined(l)||"submit"==e&&l.attempts++;var g=ob_util.isUndefined(f.attributes.action)?"":f.attributes.action.value,q=g.indexOf(":");if(0>q||16<q){var k=new String(document.URL),q=k.lastIndexOf("/"),
v=k.lastIndexOf("\\"),q=q>v?q:v;0<=q&&(k=k.substr(0,q+1),g=k+g)}var n=new ob_event(e);n.add("form._o.id",-1==h.indexOf("anonymous_form")?h:"");n.add("form._h.id",f.id);n.add("form._h.name",f.name);n.add("location",ob_util.getElementPath(c));n.add("referrer",document.URL);n.add("uri",g);c=ob_configure.forms[h].obs;g=ob_configure.forms[h].ign;k={};for(q=0;q<f.length;q++){var v=f.elements[q],p=ob_util.toLowerCase(v.nodeName),r=ob_util.toLowerCase(v.type);if("password"!=r){var s=ob_util.idOf(v),u=v.id,
w=u+"_id",x=v.name,A=x+"_name",y=m(v);if(c[w]==u||c[A]==x)y=ob_util.MD5.hash(y,!1);g[w]==u||g[A]==x||(u="form.f."+s,w="form.f."+s+"._h","checkbox"==r?ob_util.isUndefined(k[u])?k[u]=y:k[u]+=","+y:n.add(u,y),n.add(w+".type",r),n.add(w+".alt",v.alt),n.add(w+".id",v.id),n.add(w+".name",v.name),ob_util.isUndefined(l)||(n.add(u+"._o.changes",l.changes[s]),ob_util.log(h+"["+p+":"+r+":"+s+"]: changes="+l.changes[s])))}}ob_util.isUndefined(l)||(n.add("form._o.attempts",l.attempts),ob_util.log(h+": attempts="+
l.attempts));for(var z in k)ob_util.f!=typeof k[z]&&n.add(z,k[z]);setTimeout(function(){n.send()},0);"submit"==e&&ob_util.pause(10);return!0},w=function(a,b){a||(a=window.event);var e=ob_configure.w3c?a.target:a.srcElement,c=ob_util.toLowerCase(a.type),f=ob_util.toLowerCase(e.nodeName),h=ob_util.isUndefined(e.type)?f:ob_util.toLowerCase(e.type),l=ob_util.formTag(e,"form"),g=b;ob_util.isUndefined(g)&&(g=ob_util.idOf(l));var q=ob_configure.forms[g].obs,k=ob_configure.forms[g].ign;ob_util.log("sendFormFieldEvent("+
c+") for "+g+"["+f+":"+h+"]");if("password"!=h){var n=ob_util.isUndefined(l.attributes.action)?"":l.attributes.action.value,v=n.indexOf(":");if(0>v||16<v){var p=new String(document.URL),v=p.lastIndexOf("/"),r=p.lastIndexOf("\\"),v=v>r?v:r;0<=v&&(p=p.substr(0,v+1),n=p+n)}var s=new ob_event(c);s.add("form._o.id",-1==g.indexOf("anonymous_form")?g:"");s.add("form._h.id",l.id);s.add("form._h.name",l.name);s.add("location",ob_util.getElementPath(e));s.add("referrer",document.URL);s.add("uri",n);var l=ob_util.idOf(e),
p=e.id,v=p+"_id",r=e.name,u=r+"_name",n=m(e);if(q[v]==p||q[u]==r)n=ob_util.MD5.hash(n,!1);q=ob_configure.forms[g];k[v]!=p&&k[u]!=r&&(k="form.f."+l,p="form.f."+l+"._h",s.add(k,n),s.add(p+".type",h),s.add(p+".alt",e.alt),s.add(p+".id",e.id),s.add(p+".name",e.name),ob_util.isUndefined(q)||("change"==c&&q.changes[l]++,s.add(k+"._o.changes",q.changes[l]),ob_util.log(g+"["+f+":"+h+":"+l+"]: changes="+q.changes[l])));ob_util.isUndefined(q)||(s.add("form._o.attempts",q.attempts),ob_util.log(g+": attempts="+
q.attempts));setTimeout(function(){s.send()},0);return!0}},y=function(a){a||(a=window.event);if(!("click"!=ob_util.toLowerCase(a.type)&&"mouseover"!=ob_util.toLowerCase(a.type))){var b=ob_configure.w3c?a.target:a.srcElement,e=ob_util.formTag(b,"button");if(null!=e){var c="",c="img"==ob_util.toLowerCase(b.tagName)?""!=b.alt?b.alt:b.src:""!=e.title?e.title:ob_configure.w3c?e.text:e.innerText,f=e.innerHTML,h=new ob_event(ob_util.toLowerCase(a.type));h.add("referrer",document.URL);h.add("elementTagName",
e.tagName);h.add("anchor_id",e.id);h.add("anchor_name",e.name);h.add("anchor_href",f);h.add("location",ob_util.getElementPath(b));h.add("targetSelectorPath",ob_util.getElementFullSelector(b));h.add("targetInnerText",ob_util.getElementInnerText(b));h.add("title",c);h.add("port",location.port);h.add("protocol",location.protocol.substr(0,location.protocol.length-1));setTimeout(function(){h.send()},0);return!0}}},z=function(a){a||(a=window.event);if(!("click"!=ob_util.toLowerCase(a.type)&&"mouseover"!=
ob_util.toLowerCase(a.type))){var b=ob_configure.w3c?a.target:a.srcElement,e=ob_util.formTag(b,"a");if(null!=e){var c="";if("img"==ob_util.toLowerCase(b.tagName))c=""!=b.alt?b.alt:b.src;else if(""!=e.title)c=e.title;else if(c=e.getElementsByTagName("script"),0<c.length){for(var f=e.cloneNode(!0),c=f.getElementsByTagName("script");0<c.length;)c[0].parentNode.removeChild(c[0]),c=f.getElementsByTagName("script");c=ob_configure.w3c?f.text:f.innerText}else c=ob_configure.w3c?e.text:e.innerText;var h=e.href,
f=h.toString(),l=f.lastIndexOf("/"),g=f.lastIndexOf("\\"),f=f.substr((l>g?l:g)+1),l=h.indexOf(":");if(0>l||16<l){var q=new String(document.URL),l=q.lastIndexOf("/"),g=q.lastIndexOf("\\"),l=l>g?l:g;0<=l&&(q=q.substr(0,l+1),h=q+h)}var m=new ob_event(ob_util.toLowerCase(a.type));m.add("referrer",document.URL);m.add("elementTagName",e.tagName);m.add("anchor_id",e.id);m.add("anchor_name",e.name);m.add("anchor_href",f);m.add("location",ob_util.getElementPath(b));m.add("targetSelectorPath",ob_util.getElementFullSelector(b));
m.add("targetInnerText",ob_util.getElementInnerText(b));m.add("targetAlt",b.hasAttribute("alt")?b.getAttribute("alt"):"");m.add("uri",h);m.add("title",c);m.add("port",location.port);m.add("protocol",location.protocol.substr(0,location.protocol.length-1));ob_util.isFirefoxBrowser()?ob_util.addClickEvent(m):ob_util.isSafariBrowser()?m.send():setTimeout(function(){m.send()},0);return!0}}},B=function(a,b){var e=new ob_event("visibilitychange");e.add("uri",document.URL);e.add("hidden",b);setTimeout(function(){e.send()},
0)},C=function(a,b,e){a.forEach(function(a){var c=new ob_event("contentchange");c.add("uri",document.URL);c.add("eventuid",b);c.add("targetselector",e);var f=a.target;f.localName&&c.add("targetname",f.localName);f.id&&c.add("targetid",f.id);if("childList"===a.type)0<a.addedNodes.length?(f=null,1==a.addedNodes.length&&(a=a.addedNodes[0],3==a.nodeType&&(f=a.nodeValue)),f?(c.add("targettype","attribute"),c.add("attributename","innerText"),c.add("oldvalue",""),c.add("newvalue",f)):c.add("targettype",
"childadd")):0<a.removedNodes.length&&c.add("targettype","childremove");else if("attributes"===a.type)c.add("targettype","attribute"),c.add("attributename",a.attributeName),c.add("oldvalue",a.oldValue),c.add("newvalue",f.getAttribute(a.attributeName));else if("characterData"===a.type){if(3!=f.nodeType)return;c.add("targettype","attribute");c.add("attributename","innerText");c.add("oldvalue",a.oldValue);c.add("newvalue",f.nodeValue)}setTimeout(function(){c.send()},0)})},D=function(a,b,e){a||(a=window.event);
if(a=a.target?a.target:a.srcElement){var c=new ob_event("contentchange");c.add("uri",document.URL);c.add("eventid",b);c.add("targetselector",e);a.localName?c.add("targetname",a.localName):a.nodeName&&c.add("targetname",a.nodeName);a.id&&c.add("targetid",a.id);3==a.nodeType?(c.add("targettype","attribute"),c.add("attributename","innerText"),c.add("oldvalue",""),c.add("newvalue",a.nodeValue)):c.add("targettype","childadd");setTimeout(function(){c.send()},0)}},E=function(a,b,c){a||(a=window.event);var e=
a.target?a.target:a.srcElement;if(e){var f=new ob_event("contentchange");f.add("uri",document.URL);f.add("eventid",b);f.add("targetselector",c);f.add("targettype","attribute");e.localName?f.add("targetname",e.localName):e.nodeName&&f.add("targetname",e.nodeName);e.id&&f.add("targetid",e.id);if("attrChange"in a)switch(a.attrChange){case MutationEvent.ADDITION:case MutationEvent.MODIFICATION:a.attrName&&f.add("attributename",a.attrName),a.prevValue&&f.add("oldvalue",a.prevValue),a.newValue&&f.add("newvalue",
a.newValue),setTimeout(function(){f.send()},0)}}},F=function(a,b,c){a||(a=window.event);if(a=a.target?a.target:a.srcElement){var e=new ob_event("contentchange");e.add("uri",document.URL);e.add("eventid",b);e.add("targetselector",c);a.localName?e.add("targetname",a.localName):a.nodeName&&e.add("targetname",a.nodeName);a.id&&e.add("targetid",a.id);e.add("targettype","childremove");setTimeout(function(){e.send()},0)}},G=function(a,b,e){a||(a=window.event);var c=a.target?a.target:a.srcElement;if(c){var f=
new ob_event("contentchange");f.add("uri",document.URL);f.add("eventid",b);f.add("targetselector",e);f.add("targettype","attribute");c.localName?f.add("targetname",c.localName):c.nodeName&&f.add("targetname",c.nodeName);c.id&&f.add("targetid",c.id);3==c.nodeType&&(f.add("targettype","attribute"),f.add("attributename","innerText"),f.add("oldvalue",a.prevValue),f.add("newvalue",c.nodeValue),setTimeout(function(){f.send()},0))}},H=function(a,b,c,e,f,h){if(c===b&&!("update"!==e&&"add"!==e)){var l=new ob_event("jsvarchange");
l.add("name",a);l.add("action",e);ob_util.isUndefined(f)||l.add("oldvalue",f);ob_util.isUndefined(h)||l.add("newvalue",h);setTimeout(function(){l.send()},0)}};window.onerror=function(a,b,e,c,f){var h=new ob_event("jspageerror");h.add("message",a);h.add("url",b);h.add("line",e);h.add("column",c);h.add("error_stack","undefined"==typeof f||null==f?a:f.stack);setTimeout(function(){h.send()},0)};return{initialize:function(){for(var g=0;g<document.links.length;g++)f(document.links[g]);for(var m=document.getElementsByTagName("button"),
g=0;g<m.length;g++){var n=m[g];if(ob_util.isUndefined(ob_configure.isCollectionEnabled().formsubmits)||"true"==ob_configure.isCollectionEnabled().formsubmits)ob_configure.w3c?n.addEventListener("click",y,!0):n.attachEvent("onclick",y,!0);"true"==ob_configure.isCollectionEnabled().mouseovers&&(ob_configure.w3c?n.addEventListener("mouseover",y,!0):n.attachEvent("onmouseover",y))}for(g=0;g<document.forms.length;g++)k(document.forms[g],g);(ob_util.isUndefined(ob_configure.isCollectionEnabled().media)||
"true"==ob_configure.isCollectionEnabled().media)&&SasVideo.loadPlayers();g=document.getElementsByTagName("form");for(m=0;m<g.length;m++)if(n=g[m].getAttribute("action"),n=ob_util.parseUri(n),"https"==n.protocol){ob_util.ccsProtocol="https";break}a(window,"unload",c,!0);a(document.body,"DOMNodeInserted",l,!0);"interactive"==document.readyState||"complete"==document.readyState?e(null):"undefined"!==typeof document.addEventListener&&document.addEventListener("DOMContentLoaded",e,!0);"complete"==document.readyState?
b(null):a(window,"load",b,!0);v();q();if(ob_util.isUndefined(ob_configure.isCollectionEnabled().jsvars)||"true"==ob_configure.isCollectionEnabled().jsvars)if(g=(new _ob_jsvarchange_configuration).getConfig())for(var p in g){m=g[p];try{var r=m.split("."),s=r.pop();if(0<r.length){for(var u=r.pop(),n=window,w=0;w<r.length;w++)n=n[r[w]];h(p,s,n[u])}}catch(x){ob_util.log(m+" variable will not be watched: "+x)}}},findElement:function(a){var b=!1;try{0<ob_util.Sizzle(a).length&&(b=!0)}catch(e){ob_util.log("exception occurred in findElement for '"+
a+"' : "+e)}return b},findElementMatch:function(a,b){var e=[];try{var c=b[0],f=c.target,h=c.op,l=c.values,g,c="["+f+"]";"tagName"==f&&(c="*");g=a?ob_util.Sizzle(c,a):ob_util.Sizzle(c);for(c=0;c<g.length;c++){var m;m="tagName"==f?g[c].tagName.toLowerCase():g[c].getAttribute(f);for(var q=!1,n=0;n<l.length;n++){if(ob_util.strOp(h,m,l[n]))for(var q=!0,v=1;v<b.length;v++){var k=b[v],p=k.target,r=k.op,s=k.values;m="tagName"==p?g[c].tagName.toLowerCase():g[c].getAttribute(p);for(var u=!1,w=0;w<s.length;w++)if(ob_util.strOp(r,
m,s[w])){u=!0;break}if(!u){q=!1;break}}if(q){e.push(g[c]);break}}}}catch(x){ob_util.log("exception occurred in findElementMatch: "+x)}return e},collectTerm:function(a,b,c,e){var f="",h="",l;try{h=ob_util.Sizzle(a);if(ob_util.isUndefined(h))return;l=h[0];null!=l&&(f=this.getContent(l,b,c,e))}catch(g){ob_util.log("exception occurred in collectTerm for '"+a+"["+b+"]': "+g)}return null==f?f:f.trim()},filterValue:function(a,b,c){var e=a;if("before"==b)b=e.indexOf(c),e=0<=b?e.substring(0,b):a;else if("before_last"==
b)b=e.lastIndexOf(c),e=0<=b?e.substring(0,b):a;else if("after"==b)b=e.indexOf(c),e=0<=b?e.substring(b+c.length,e.length):a;else if("after_last"==b)b=e.lastIndexOf(c),e=0<=b?e.substring(b+c.length,e.length):a;else if("between"==b){c=c.split("__&&__");b=e.indexOf(c[0]);var f=e.indexOf(c[1],b+c[0].length),e=0<=b&&0<=f?e.substring(b+c[0].length,f):a}else"regex"==b&&(a=RegExp(c).exec(a))&&0<a.length&&(e=a[a.length-1]);return e},openWindow:function(a,b,c,e,f,h,l){var g="";!1!=c&&(g+="height="+c+",");!1!=
e&&(g+="width="+e+",");!0==f&&(g+="menubar=no,status=no,toolbar=no,");!0==h&&(g+="scrollbars=no,resizable=no,");!0==l&&(g+="titlebar=no");return window.open(a,b,g)},instrumentDivClick:function(a,b,c){a=document.getElementById(a);null!=a&&(ob_configure.w3c?a.addEventListener("click",function(){trackClick(b,c)},!0):a.attachEvent("onclick",function(){trackClick(b,c)}))},getContent:function(a,b,c,e){var f;if("innerHTML"==b)f=a.innerHTML;else if("innerText"==b)f=a.textContent?a.textContent:a.innerText;
else if("outerHTML"==b)f=a.outerHTML;else{if("value"!=b&&(a=a.attributes.getNamedItem(b),!a))return f;f=a.value}c&&(0<c.length&&e&&0<e.length)&&(f=this.filterValue(f,c,e));return f=f.trim()}}}(),_ob_jsvar=function(){var a=Object.observe?!0:!1,b=function(a,b,c){try{Object.defineProperty(a,b,{enumerable:!1,configurable:!0,writeable:!1,value:c})}catch(k){a[b]=c}},c=function(a,b){var c=a[b],k=function(){return c},p=function(k){var p=c;c=k;if(p!==k&&a.o_watchers&&a.o_watchers.list)for(var r=0;r<a.o_watchers.list.length;r++)a.o_watchers.list[r].call(a,
b,"update",p,k)};try{Object.defineProperty?Object.defineProperty(a,b,{get:k,set:p,enumerable:!0,configurable:!0}):Object.prototype.__defineGetter__&&Object.prototype.__defineSetter__&&(Object.prototype.__defineGetter__.call(a,b,k),Object.prototype.__defineSetter__.call(a,b,p))}catch(r){}};return{watch:function(e,f){if(e instanceof Object||ob_util.isArray(e))if(a){var g=function(a){a.forEach(function(a){f(a.name,a.type,a.oldValue,a.object[a.name])})};try{Object.observe(e,g)}catch(k){}}else{e.o_watchers||
b(e,"o_watchers",{});e.o_watchers.list||(e.o_watchers.list=[]);for(g=0;g<e.o_watchers.list.length;g++)if(e.o_watchers.list[g]===f)return;e.o_watchers.list.push(f);if(ob_util.isArray(e))for(var p=0;p<e.length;p++)c(e,p);else if("object"==typeof e)for(p in e)e.hasOwnProperty(p)&&c(e,p)}},unwatch:function(b,c){if(a)Object.unobserve(b,c);else if(b.o_watchers&&b.o_watchers.list)for(var g=0;g<b.o_watchers.list.length;g++)if(b.o_watchers.list[g]===c){b.o_watchers.list.splice(g,1);break}}}}();
function ob_event(a,b){this.dataElements=[];this.event=a;this.data="";if(ob_util.isUndefined(b)||null==b){var c="";null!=ob_util.ccsProtocol&&(c+=ob_util.ccsProtocol+":");this.url=c+=ob_configure.ccs}else this.url=b;this.basicProperties={};this.basicProperties.visitor=ob_configure.getVisitorId();this.basicProperties.session=ob_configure.getSessionId();this.basicProperties.domain=ob_configure.getDomain();this.basicProperties.load_id=ob_configure.getLoadId();var c=(new Date).getTime(),e=0;0<ob_util.lastActivity&&
(e=c-ob_util.lastActivity);ob_util.lastActivity=c;ob_util.lastInactivePeriod=Math.max(e,ob_util.lastInactivePeriod);this.basicProperties.hb=ob_util.lastInactivePeriod;this.basicProperties.version="1.0.10";this.basicProperties.event=this.event;this.basicProperties.flags="";this.basicProperties.cts=+new Date;this.basicProperties.csn=ob_util.nsn();ob_util.newvid&&(ob_util.newvid=!1,this.basicProperties.flags+="|nv");ob_util.newsid&&(ob_util.newsid=!1,this.basicProperties.flags+="|ns",null!=
ob_util.oldsid&&(this.basicProperties["previous.session"]=ob_util.oldsid,ob_util.oldsid=null));ob_util.webmarketing&&(this.basicProperties.flags+="|wm");var c=this.getTermConfig("global"),e=this.getTermConfig(this.event),f=this.getTermConfig("find"),g;for(g in c)this.add(g,c[g]);for(g in e)"function"==typeof e[g]?this.add(g,e[g]()):this.add(g,e[g]);for(g in f)this.add(g,f[g]);ob_configure.sendMeta[this.event]&&this.addMeta();ob_configure.sendCookies[this.event]&&this.addCookies();ob_configure.sendJsvars[this.event]&&
this.addJsvars();for(g in this.basicProperties)this.add(g,this.basicProperties[g])}
ob_event.prototype.send=function(a){if(this.validate()){ob_util.isFirefoxBrowser()&&("click"!=this.event&&"cartaction"!=this.event)&&ob_util.sendClickEvents(a);this.data="";for(var b in this.dataElements)typeof this.dataElements[b]!=ob_util.f&&(0<this.data.length&&(this.data+="&"),this.data+=encodeURIComponent(b)+"="+encodeURIComponent(this.dataElements[b]));_o_ajax.sendEvent(this.url,this.excludeDataElements(this.data),a)}};
ob_event.prototype.validate=function(){if(!ob_configure.validateEvents)return!0;var a=!0,b=this.basicProperties.visitor,c=this.basicProperties.session,e=this.basicProperties.domain,f=this.basicProperties.event;if(a&&(!b||null==b||0==b.length))a=!1;if(a&&(!c||null==c||0==c.length))a=!1;if(a&&(!e||null==c||0==e.length))a=!1;if(a&&(!f||null==c||0==f.length))a=!1;return a};ob_event.prototype.termConfiguration=function(){return{}};ob_event.prototype.getTermConfig=function(a){return this.termConfiguration()[a]};
ob_event.prototype.findElements=function(a){var b={},c;for(c in a)b[c]="",0<ob_util.Sizzle(a[c]).length&&(b[c]="found");return b};ob_event.prototype.add=function(a,b){ob_util.isUndefined(a)||(ob_util.isUndefined(b)&&(b=""),this.dataElements[a]=b)};ob_event.prototype.addMeta=function(){var a=document.getElementsByTagName("META"),b="",c;for(c in a){var e=a[c],b=""!=e.name?e.name:""!=e.httpEquiv?e.httpEquiv:c;typeof e!=ob_util.f&&!ob_util.isUndefined(b)&&this.add("meta."+b,e.content)}};
ob_event.prototype.addCookies=function(){for(var a=(new String(document.cookie)).split("; "),b=0;b<a.length;b++)with(a[b]){var c=indexOf("="),e="",f="";0<=c&&(e=substr(0,c),f=unescape(substr(c+1)));this.add("cookie."+e,f,!0,4)}};
ob_event.prototype.addJsvars=function(){if(ob_util.isUndefined(ob_configure.isCollectionEnabled().jsvars)||"true"==ob_configure.isCollectionEnabled().jsvars){var a=(new _ob_jsvar_configuration).getConfig();if(a)for(var b in a){var c=a[b];try{for(var e=c.split("."),f=e.pop(),g=window,k=0;k<e.length;k++)g=g[e[k]];var p=g[f];if(ob_util.isArray(p)){for(var g="[",r=0;r<p.length;r++)0<r&&(g+=","),g+=p[r];g+="]";this.add("jsvar."+b,g)}else if("object"==typeof p)for(r in p)p.hasOwnProperty(r)&&this.add("jsvar."+
b+"."+r,p[r]);else("number"==typeof p||"string"==typeof p||"boolean"==typeof p)&&this.add("jsvar."+b,p)}catch(s){ob_util.log(c+" variable will not be reported: "+s)}}}};ob_event.prototype.excludeDataElements=function(a){var b=this.getTermConfig("exclude"),c;for(c in b)-1!=a.indexOf(b[c])&&(a=a.replace(RegExp(b[c]+"=[^\\&]*\\&","g"),""));return a};
var _o_ajax=function(){var a=function(a,b){!0==a.aborted?(ob_util.log("o_ajax handleResponse: aborted, eventname = ["+a.oe+"]"),_o_ajax.cancelTimer(a)):ob_util.isUndefined(a.readyState)?ob_util.log("o_ajax handleResponse: readyState=undefined, eventname = ["+a.oe+"]"):4==a.readyState&&(ob_util.log("o_ajax handleResponse: readState=4,  eventname = ["+a.oe+"]"),_o_ajax.cancelTimer(a))},b=function(a,b,c){ob_util.log("o_ajax timeout: oto = ["+a.oto+"], to = ["+c+"] ms, eventname = ["+a.oe+"]");a.aborted&&
(a.aborted=!0);a.abort()},c=function(a,b,c,e,r){try{var s=new XDomainRequest;s.timeout=ob_util.isUndefined(ob_configure.timeout)?500:ob_configure.timeout;s.onerror=function(){ob_util.log("o_ajax_ie8: ERROR")};s.onload=function(){ob_util.log("o_ajax_ie8: ONLOAD");e(s,r)};s.onprogress=function(){ob_util.log("o_ajax_ie8: PROGRESS")};s.ontimeout=function(){ob_util.log("o_ajax_ie8: TIMEOUT")};if(ob_util.logging){var x="";if(null!=b){var u=b.indexOf("event=");-1!=u&&(x=b.substring(u+6),u=x.indexOf("&"),
-1!=u&&(x=x.substring(0,u)))}s.oe=x;ob_util.log("o_ajax.ie8_send data: eventname = ["+x+"]")}if("POST"==c)s.open(c,a),s.send(b);else{var v=null!=b?0<a.indexOf("?")?"&"+b:"?"+b:"";s.open(c,a+v);s.send()}}catch(q){ob_util.log("o_ajax.ie8_send(): "+q)}},e=function(e,g,k,p,r,s){ob_util.isUndefined(p)&&(p=!0);if(ob_util.isUndefined(r)||null==r)r=a;if(ob_util.isIE8Browser())c(e,g,k,r,s);else try{var x=ob_util.isUndefined(ob_configure.timeout)?500:ob_configure.timeout,u=function(){try{return new (this.XMLHttpRequest||
ActiveXObject)("MSXML2.XMLHTTP.3.0")}catch(a){}}();u.onreadystatechange=function(){r(u,s)};typeof u.onloadend==ob_util.f&&(u.onloadend=function(){ob_util.log("o_ajax onloadend: eventname = ["+u.oe+"]");cancelTimer(u)});!1!=p&&(typeof u.onloadstart==ob_util.f?u.onloadstart=function(){u.oto=setTimeout(function(){b(u,e,x)},x);ob_util.log("o_ajax setTimeout: oto = ["+u.oto+"], to = ["+x+"] ms")}:(u.oto=setTimeout(function(){b(u,e,x)},x),ob_util.log("o_ajax setTimeout: oto = ["+u.oto+"], to = ["+x+"] ms")));
if("POST"==k)u.open(k,e,p),u.setRequestHeader("Content-Type","application/x-www-form-urlencoded;charset=UTF-8");else{var v=null!=g?e.indexOf("?")?"&"+g:"?"+g:"";u.open(k,e+v,p)}!1!=p&&(u.withCredentials=!0);if(ob_util.logging){k="";if(null!=g){var q=g.indexOf("event=");-1!=q&&(k=g.substring(q+6),q=k.indexOf("&"),-1!=q&&(k=k.substring(0,q)))}u.oe=k;ob_util.log("o_ajax send data: eventname = ["+k+"], data = ["+g+"]")}u.send(g)}catch(h){ob_util.log("o_ajax.send() error: "+h)}};return{sendEvent:function(a,
b,c){e(a,b,"POST",c)},fetchContent:function(a,b,c,p,r){e(a,b,"GET",c,p,r)},cancelTimer:function(a){a.oto?(ob_util.log("o_ajax clearTimer: oto = ["+a.oto+"], eventname = ["+a.oe+"]"),clearTimeout(a.oto),a.oto=null):ob_util.log("o_ajax clearTimer: no timer to clear, eventname = ["+a.oe+"]")}}}();function ob_injector(){}ob_injector.prototype.getSpotDefinitions=function(){return{}};ob_injector.prototype.injectAll=function(){var a=this.getSpotDefinitions();if(a)for(var b in a)(new ob_inject(b,a[b])).inject()};
function ob_inject(a,b){this.spotId=a;this.spot=b}
ob_inject.prototype.inject=function(){var a=this.spot.divId,b=document.querySelectorAll(a)[0];if(null!=b){ob_util.log("inject(spot="+this.spotId+") into HTML div "+a);"DIV"!=b.tagName&&(b=b.parentNode);var a=this.spot.service,c=ob_configure.csu;if(!ob_util.isUndefined(a.p)){var e=!0,f;for(f in a.p){var g=a.p[f];!ob_util.isUndefined(g)&&(null!=g&&"null"!=g)&&(c+=(e?"?":"&")+f+"="+g,e=!1)}}_o_ajax.fetchContent(c,null,!0,this.handleInjectResponse,b)}else ob_util.log("inject(spot="+this.spotId+"): HTML div["+
div_xpath+"] not found")};ob_inject.prototype.handleInjectResponse=function(a,b){!0==a.aborted?_o_ajax.cancelTimer(a):4==a.readyState&&(_o_ajax.cancelTimer(a),200==a.status&&0<a.responseText.length&&null!=b&&(b.innerHTML=a.responseText))};
var ob_cart_action=function(){return{add:function(a,b,c,e,f,g,k){var p=f;if(!a&&!b&&!c)ob_util.log("cart add: one of id, name, or sku is required.");else if(e?"number"!=typeof e&&(e=parseInt(e),isNaN(e)&&(ob_util.log("cart add: qty is not a valid number. defaulting to 1."),e=1)):e=1,f){if("number"!=typeof f&&(f=parseFloat(f),isNaN(f))){ob_util.log("cart add: price is not a valid number.");return}g?"boolean"!=typeof g&&(ob_util.log("cart add: isUnitPrice is not a valid boolean."),g=!0):g=!0;g||(p=
f/e);var r=new ob_event("cartaction");r.add("action","add");a&&r.add("product_id",a);b&&r.add("product_name",b);c&&r.add("product_sku",c);r.add("product_quantity",e);r.add("product_unit_price",p.toFixed(2));if(void 0!=k&&null!=k)for(var s in k)k.hasOwnProperty(s)&&k[s]&&r.add(s,k[s]);setTimeout(function(){r.send()},0)}else ob_util.log("cart add: price is undefined, but is required.")},addFailed:function(a){if(a){var b=new ob_event("cartaction");b.add("action","addFailed");b.add("product_id",a);setTimeout(function(){b.send()},
0)}else ob_util.log("cart addFailed: id is undefined, but is required.")},remove:function(a,b,c,e,f,g,k,p){if(!a&&!b&&!c)ob_util.log("cart remove: id,name,sku are undefined, but at least one is required.");else{f&&"number"!=typeof f&&(f=parseFloat(f),isNaN(f)?(ob_util.log("cart remove: unit_price is not a valid number."),f=""):f=f.toFixed(2));var r=new ob_event("cartaction");r.add("action","remove");r.add("product_id",a);r.add("product_name",b);r.add("product_sku",c);r.add("product_quantity",e);r.add("product_unit_price",
f);r.add("cart_id_internal",g);r.add("cart_name",k);r.add("cart_type",p);ob_util.isFirefoxBrowser()?ob_util.addClickEvent(r):ob_util.isSafariBrowser()?r.send():setTimeout(function(){r.send()},0)}},update:function(a,b){if(a)if(b){if("number"!=typeof b&&(b=parseInt(b),isNaN(b))){ob_util.log("cart update: qty is not a number.");return}var c=new ob_event("cartaction");c.add("action","update");c.add("product_id",a);c.add("product_quantity",b);setTimeout(function(){c.send()},0)}else ob_util.log("cart update: qty is undefined, but is required.");
else ob_util.log("cart update: id is undefined, but is required.")}}}(),ob_cart=function(){function a(a,b,f,g){var k=new ob_event("cartitem");k.add("cart_id_internal",a);k.add("cart_name",b);k.add("cart_type",f);f=b=a=!1;for(var p in g)g.hasOwnProperty(p)&&g[p]&&(k.add(p,g[p]),"product_id"==p&&(a=!0),"product_name"==p&&(b=!0),"product_sku"==p&&(f=!0));(a||b||f)&&setTimeout(function(){k.send()},0)}function b(a,b,f,g){var k=new ob_event("cart");k.add("cart_id_internal",a);k.add("cart_name",b);k.add("cart_type",
f);a=g.getDetails();for(var p in a)a.hasOwnProperty(p)&&a[p]&&k.add(p,a[p]);setTimeout(function(){k.send()},0)}return{contents:function(){var a=[];this.addItem=function(b,f,g,k,p,r,s,x,u){var v={};v.product_id=b;v.product_name=f;v.product_sku=g;v.product_quantity=k;"number"==typeof p&&(p=p.toFixed(2));v.product_unit_price=p;v.product_group=r;v.availability_message=s;v.shipping_message=x;v.saving_message=u;a.push(v)};this.addContent=function(b){a.push(b)};this.getItems=function(){return a};this.clearItems=
function(){a=[]}},details:function(){var a={};this.setDetails=function(b,f,g,k,p,r,s,x,u,v,q,h,l,n){a.cart_id=b;"number"==typeof f&&(f=f.toFixed(2));a.total_cart_value=f;"number"==typeof g&&(g=g.toFixed(2));a.tax=g;"number"==typeof k&&(k=k.toFixed(2));a.shipping_cost=k;a.payment_type=p;a.delivery_type=r;a.shipping_city=s;a.shipping_region=x;a.shipping_postcode=u;a.shipping_country=v;a.billing_city=q;a.billing_region=h;a.billing_postcode=l;a.billing_country=n};this.addDetails=function(b){for(var f in b)b.hasOwnProperty(f)&&
b[f]&&(a[f]=b[f])};this.getDetails=function(){return a};this.clearDetails=function(){a={}}},showProductDetails:function(b,e,f,g){g=g.getItems();for(var k=0;k<g.length;k++)a(b,e,f,g[k])},showCartDetails:function(a,e,f,g){b(a,e,f,g)}}}();function _ob_cart_configuration(){}_ob_cart_configuration.prototype.getCartConfig=function(){};_ob_cart_configuration.prototype.getCheckoutConfig=function(){};_ob_cart_configuration.prototype.getPurchaseConfig=function(){};
var _ob_cart_handlers=function(){function a(a,b,f,g,k,p,r,s){return function(x){ob_cart_action.remove(a,b,f,g,k,p,r,s)}}function b(b,e){if(b)for(var f in b)try{var g=b[f],k=g.name;if(g.selector){var p=ob_util.Sizzle(g.selector);if(0!=p.length){for(var r=g.item,s=new ob_cart.contents,x=0;x<p.length;x++){var u={},v=!0;for(prop in r){var q=r[prop];if(q){for(var h=q,l=p[x],n=null,m=void 0,h=[].concat(h),A=0;A<h.length;A++){var w=h[A];if(w&&w.s){var y;y=l?ob_util.Sizzle(w.s,l):ob_util.Sizzle(w.s);if(0!=
y.length&&(m=_ob_dom.getContent(y[0],w.a,w.f,w.p))){n=m;break}}}if(value=n)u[prop]=value,v=!1}}if(!v){s.addContent(u);var z=g.removetargets;if(z)for(var B=_ob_dom.findElementMatch(p[x],z),v=0;v<B.length;v++)ob_configure.w3c?B[v].addEventListener("click",a(u.product_id,u.product_name,u.product_sku,u.product_quantity,u.product_unit_price,f,k,e)):B[v].attachEvent("onclick",a(u.product_id,u.product_name,u.product_sku,u.product_quantity,u.product_unit_price,f,k,e))}}ob_cart.showProductDetails(f,k,e,s);
var C=new ob_cart.details;ob_cart.showCartDetails(f,k,e,C)}}}catch(D){ob_util.log("exception occurred during cart scraping: "+D)}}return{scrapeHandler:function(){b((new _ob_cart_configuration).getCartConfig(),"cartview");b((new _ob_cart_configuration).getCheckoutConfig(),"checkout");b((new _ob_cart_configuration).getPurchaseConfig(),"purchase")}}}();function _ob_contentvisible_configuration(){}_ob_contentvisible_configuration.prototype.getConfig=function(){return _ob_contentvisible_configuration()};
function _ob_jsvar_configuration(){}_ob_jsvar_configuration.prototype.getConfig=function(){return _ob_jsvar_configuration()};function _ob_jsvarchange_configuration(){}_ob_jsvarchange_configuration.prototype.getConfig=function(){return _ob_jsvarchange_configuration()};
var SasVideo={_silverlight:{},_brightcove:{},_youtube:{},_osmf:{},_wmp:{},_players:[],loadPlayers:function(){var a=["video","audio","embed[html5='true']"],b=["object[type='application/x-oleobject']"],c=["object[type='video/quicktime']"],e=["object[type='application/x-shockwave-flash'][data*='StrobeMediaPlayback.swf']"],f,g,k,p;f=!1;g=document.getElementsByTagName("iframe");for(k=g.length;k--;)/youtube.com\/embed/.test(g[k].src)&&(f=!0,-1===g[k].src.indexOf("enablejsapi=")&&(g[k].src+=(-1===g[k].src.indexOf("?")?
"?":"&")+"enablejsapi=1"));f&&this.loadYouTubeIframeAPI();for(k=0;k<a.length;k++){g=ob_util.Sizzle(a[k]);for(p=0;p<g.length;p++)f=new SasVideo.Html5(g[p]),this._players.push[f]}if(/MSIE/.test(navigator.userAgent)&&"Win32"==navigator.platform)for(k=0;k<b.length;k++){g=ob_util.Sizzle(b[k]);for(p=0;p<g.length;p++)f=new SasVideo.WindowsMediaPlayer(g[p]),this._players.push(f)}for(k=0;k<c.length;k++){g=ob_util.Sizzle(c[k]);for(p=0;p<g.length;p++)f=new SasVideo.Quicktime(g[p]),this._players.push(f)}for(k=
0;k<e.length;k++){g=ob_util.Sizzle(e[k]);for(p=0;p<g.length;p++)f=new SasVideo.Osmf(g[p]),this._players.push(f)}},unloadPlayers:function(){for(var a,b=0;b<window._players.length;b++)a=window._players[b],a=a.send("exit"),_send(a)},loadYouTubeIframeAPI:function(){var a=document.createElement("script"),b=document.getElementsByTagName("script")[0];a.src="//www.youtube.com/iframe_api";b.parentNode.insertBefore(a,b)},addSilverlight:function(a){var b={};SasVideo.createSilverlight(a,b);return b},createSilverlight:function(a,
b){if("Canvas"==a.toString())for(var c,e=0;e<a.children.count;e++)c=a.children.getItem(e),"MediaElement"==c.toString()?(new SasVideo.SilverLight(c),b[c.name]=c):sasVideo.createSilverlight(c,b)},getSilverlight:function(a){return SasVideo._silverlight.hasOwnProperty(a)?SasVideo._silverlight[a]._player:null},handleBrightcove:function(a){var b=SasVideo._brightcove[a.target.experience.id];b.set(a);"mediaPlay"==a.type?(ob_util.log("Brightcove media event [mediaPlay]"),b.start()):"mediaStop"==a.type&&(ob_util.log("Brightcove media event [mediaStop]"),
b.stop())},osmfRegister:function(a){null==a.getState?setTimeout(function(){SasVideo.osmfRegister(a)},1E3):(a.addEventListener("mediaPlayerStateChange","SasVideo.osmfStateChange"),a.addEventListener("currentTimeChange","SasVideo.osmfTimeChange"),a.addEventListener("complete","SasVideo.osmfComplete"),a.addEventListener("durationChange","SasVideo.osmfDurationChange"),"playing"==a.getState()&&this.play())},osmfStateChange:function(a,b){if(SasVideo._osmf.hasOwnProperty(b)){var c=SasVideo._osmf[b];"playing"==
a?(ob_util.log("OSMF media event [playing]"),c.play()):"paused"==a&&(ob_util.log("OSMF media event [paused]"),c.pause())}},osmfTimeChange:function(a,b){SasVideo._osmf.hasOwnProperty(b)&&ob_util.log("OSMF media event [timechange]")},osmfDurationChange:function(a,b){SasVideo._osmf.hasOwnProperty(b)&&(ob_util.log("OSMF media event [durationchange]"),_SasVideo.osmf[b]._duration=parseInt(a))},osmfComplete:function(a,b){SasVideo._osmf.hasOwnProperty(b)&&(ob_util.log("OSMF media event [complete]"),_osmf[b].end())},
handleQuicktime:function(a){var b=a.target.__player;"qt_play"==a.type?(ob_util.log("Quicktime media event [play]"),b.play()):"qt_pause"==a.type?(ob_util.log("Quicktime media event [pause]"),b.pause()):"qt_ended"==a.type&&(ob_util.log("Quicktime media event [ended]"),b.end())},getWindowsMedia:function(a){return SasVideo._wmp.hasOwnProperty(a)?SasVideo._wmp[a]:null},Html5:function(a){this._player=a;this._player.__player=this;this._type="Html5";this._source=null;this._duration=0;this._seeking=!1;ob_util.isIE8Browser()?
(this._player.attachEvent("play",SasVideo.Html5_handle),this._player.attachEvent("pause",SasVideo.Html5_handle),this._player.attachEvent("ended",SasVideo.Html5_handle),this._player.attachEvent("seeking",SasVideo.Html5_handle),this._player.attachEvent("seeked",SasVideo.Html5_handle),this._player.attachEvent("durationchange",SasVideo.Html5_handle)):(this._player.addEventListener("play",SasVideo.Html5_handle),this._player.addEventListener("pause",SasVideo.Html5_handle),this._player.addEventListener("ended",
SasVideo.Html5_handle),this._player.addEventListener("seeking",SasVideo.Html5_handle),this._player.addEventListener("seeked",SasVideo.Html5_handle),this._player.addEventListener("durationchange",SasVideo.Html5_handle))}};SasVideo.Html5.prototype.start=function(a){this._position=0;this.send("start")};SasVideo.Html5.prototype.playing=function(a){a=parseInt(this._player.currentTime);this._position!=a&&(this._position=a,this.send("playing"))};
SasVideo.Html5.prototype.stop=function(a){this._position=0;this.send("stop")};SasVideo.Html5.prototype.end=function(a){this.send("end")};SasVideo.Html5.prototype.setDuration=function(a){this._duration=a};SasVideo.Html5.prototype.seeking=function(a){!1==this._player.paused&&!1==this._seeking&&(this._seeking=!0,this.send("stop"))};SasVideo.Html5.prototype.seeked=function(a){!1==this._player.paused&&(this.send("start"),this._seeking=!1)};
SasVideo.Html5.prototype.send=function(a){var b=parseInt(this._player.currentTime),c=this._duration;0==c&&!1==isNaN(this._player.duration)&&(c=parseInt(this._player.duration));ob_util.log("send ("+this._type+") : "+a+" ("+b+" out of "+c+")");var e=new ob_event("media");e.add("player_id",this._player.id);e.add("media",this._source);e.add("media_player",this._type);e.add("media_position",b);e.add("media_duration",c);e.add("media_action",a);setTimeout(function(){e.send()},0)};
SasVideo.Html5_handle=function(a){var b=a.target.__player;b._source=a.target.currentSrc;"play"==a.type?(ob_util.log("Html5 media event [play]"),b.start()):"pause"==a.type?(ob_util.log("Html5 media event [pause]"),b.stop()):"ended"==a.type?(ob_util.log("Html5 media event [ended]"),b.end()):"timeupdate"==a.type?(ob_util.log("Html5 media event [timeupdate]"),!1==b._player.paused&&b.playing()):"durationchange"==a.type?(ob_util.log("Html5 media event [durationchange]"),a.target.hasOwnProperty("duration")&&
b.setDuration(parseInt(a.target.duration))):"seeking"==a.type?(ob_util.log("Html5 media event [seeking]"),b.seeking(a)):"seeked"==a.type&&(ob_util.log("Html5 media event [seeked]"),b.seeked(a))};SasVideo.SilverLight=function(a){this._playing=!1;this._player=a;this._type="Silverlight";SasVideo._silverlight[a.name]=this;this._player.addEventListener("CurrentStateChanged",SasVideo.SilverLight_state);this._player.addEventListener("MediaEnded",SasVideo.SilverLight_end)};
SasVideo.SilverLight.prototype.state=function(){"Playing"==this._player.currentState?(ob_util.log("SilverLight media event [playing]"),!1==this._playing&&(this._playing=!0,this.play())):"Paused"==this._player.currentState&&(ob_util.log("SilverLight media event [paused]"),this._playing&&(this._playing=!1,this.pause()))};SasVideo.SilverLight.prototype.play=function(a){this.send("start")};SasVideo.SilverLight.prototype.pause=function(a){this.send("stop")};
SasVideo.SilverLight.prototype.end=function(){ob_util.log("SilverLight media event [end]");this.send("end")};
SasVideo.SilverLight.prototype.send=function(a){var b=parseInt(this._player.position.seconds),c=parseInt(this._player.naturalDuration.seconds);ob_util.log("send ("+this._type+") : "+a+" ("+b+" out of "+c+")");var e=new ob_event("media");e.add("player_id",this._player.name);e.add("media",this._player.Source);e.add("media_player",this._type);e.add("media_duration",c);e.add("media_position",b);e.add("media_action",a);setTimeout(function(){e.send()},0)};SasVideo.SilverLight_state=function(a){SasVideo._silverlight[a.name].state()};
SasVideo.SilverLight_end=function(a){SasVideo._silverlight[a.name].end()};SasVideo.Brightcove=function(a){if(null!=(this._player=a))this._type="Brightcove",this._id=a.experience.id,this._position=this._duration=0,SasVideo._brightcove[this._id]=this,a.addEventListener(brightcove.api.events.MediaEvent.PLAY,SasVideo.handleBrightcove),a.addEventListener(brightcove.api.events.MediaEvent.STOP,SasVideo.handleBrightcove)};SasVideo.Brightcove.prototype.start=function(a){this.send("start")};
SasVideo.Brightcove.prototype.playing=function(a){};SasVideo.Brightcove.prototype.stop=function(a){this.send("stop")};SasVideo.Brightcove.prototype.end=function(a){this.send("end")};SasVideo.Brightcove.prototype.set=function(a){this._duration=parseInt(a.duration);this._position=parseInt(a.position);this._source=a.media.FLVFullLengthURL};
SasVideo.Brightcove.prototype.send=function(a){var b=this._position,c=this._duration;ob_util.log("send ("+this._type+") : "+a+" ("+b+" out of "+c+")");var e=new ob_event("media");e.add("player_id",this._id);e.add("media",this._source);e.add("media_player",this._type);e.add("media_position",b);e.add("media_duration",c);e.add("media_action",a);setTimeout(function(){e.send()},0)};
SasVideo.YouTube=function(a,b,c,e){this._player=a;!c&&a.id&&(c=a.id);!e&&a.src&&(e=a.src);!e&&a.data&&(e=a.data);this._id=c;this._src=e;this._type="YouTube";SasVideo._youtube[c]=this;b?(b="YouTube_"+c.replace(/([^_a-z0-9]+)/g,""),e="",e="SasVideo."+b+" = function(state){",e+='var player = SasVideo._youtube["'+c+'"];',e+="var state_wrapper = {};",e+="state_wrapper['data'] = state;",e+="player.state(state_wrapper);",e+="}",eval(e),a.addEventListener("onStateChange","SasVideo."+b)):a.addEventListener("onStateChange",
function(){return function(a){SasVideo._youtube[c].state(a)}}())};SasVideo.YouTube.prototype.state=function(a){1==a.data?(ob_util.log("YouTube media event [play]"),this.play()):2==a.data?(ob_util.log("YouTube media event [pause]"),this.pause()):0==a.data&&(ob_util.log("YouTube media event [end]"),this.end())};SasVideo.YouTube.prototype.play=function(){this.send("start")};SasVideo.YouTube.prototype.pause=function(a){this.send("stop")};SasVideo.YouTube.prototype.end=function(a){this.send("end")};
SasVideo.YouTube.prototype.send=function(a){var b=parseInt(this._player.getCurrentTime()),c=parseInt(this._player.getDuration());ob_util.log("send ("+this._type+") : "+a+" ("+b+" out of "+c+")");var e=new ob_event("media");e.add("player_id",this._id);e.add("media",this._src);e.add("media_player",this._type);e.add("media_duration",c);e.add("media_position",b);e.add("media_action",a);setTimeout(function(){e.send()},0)};
function onYouTubeIframeAPIReady(){if(ob_util.isUndefined(ob_configure.isCollectionEnabled().media)||"true"==ob_configure.isCollectionEnabled().media)for(var a=document.getElementsByTagName("iframe"),b=a.length;b--;)/youtube.com\/embed/.test(a[b].src)&&new SasVideo.YouTube(new YT.Player(a[b]),0,a[b].id?a[b].id:b,a[b].src)}
function onYouTubePlayerReady(a){(ob_util.isUndefined(ob_configure.isCollectionEnabled().media)||"true"==ob_configure.isCollectionEnabled().media)&&new SasVideo.YouTube(document.getElementById(a),1)}SasVideo.Osmf=function(a){this._type="OSMF";this._player=a;SasVideo._osmf[this._player.getAttribute("name")]=this;this._duration=0;SasVideo.osmfRegister(a)};SasVideo.Osmf.prototype.play=function(){this.send("start")};SasVideo.Osmf.prototype.pause=function(){this.send("stop")};
SasVideo.Osmf.prototype.end=function(){this.send("end")};SasVideo.Osmf.prototype.seek=function(){this.send("seek")};
SasVideo.Osmf.prototype.send=function(a){var b=parseInt(this._player.getCurrentTime()),c=this._duration;0==c&&!1==isNaN(this._player.getDuration())&&(c=parseInt(this._player.getDuration()));ob_util.log("send ("+this._type+") : "+a+" ("+b+" out of "+c+")");var e=new ob_event("media");e.add("player_id",this._player.getAttribute("id"));e.add("media",this._player.getSrc());e.add("media_player",this._type);e.add("media_duration",c);e.add("media_position",b);e.add("media_action",a);setTimeout(function(){e.send()},
0)};
SasVideo.Quicktime=function(a){this._player=a;this._player.__player=this;this._type="Quicktime";ob_util.isIE8Browser()?(this._player.attachEvent("qt_play",SasVideo.handleQuicktime),this._player.attachEvent("qt_pause",SasVideo.handleQuicktime),this._player.attachEvent("qt_ended",SasVideo.handleQuicktime),this._player.attachEvent("qt_timechanged",SasVideo.handleQuicktime)):(this._player.addEventListener("qt_play",SasVideo.handleQuicktime),this._player.addEventListener("qt_pause",SasVideo.handleQuicktime),this._player.addEventListener("qt_ended",
SasVideo.handleQuicktime),this._player.addEventListener("qt_timechanged",SasVideo.handleQuicktime))};SasVideo.Quicktime.prototype.play=function(){this._position=0;this.send("start")};SasVideo.Quicktime.prototype.pause=function(){this.send("stop")};SasVideo.Quicktime.prototype.end=function(){this.send("end")};SasVideo.Quicktime.prototype.playing=function(a){a=parseInt(this._player.GetTime()/1E3);this._position!=a&&(this._position=a,this.send("playing"))};SasVideo.Quicktime.prototype.seek=function(){this.send("seek")};
SasVideo.Quicktime.prototype.send=function(a){var b=parseInt(this._player.GetTime()/1E3),c=parseInt(this._player.GetDuration()/1E3);ob_util.log("send ("+this._type+") : "+a+" ("+b+" out of "+c+")");var e=new ob_event("media");e.add("",this._player.id);e.add("player_id",this._player.GetMovieName());e.add("media",this._player.GetURL());e.add("media_player",this._type);e.add("media_duration",c);e.add("media_position",b);e.add("media_action",a);setTimeout(function(){e.send()},0)};
SasVideo.WindowsMediaPlayer=function(a){this._player=a;this._player.__player=this;this._type="WindowsMediaPlayer";this._position=0;SasVideo._wmp[a.id]=this;var b="wmpstate_"+a.id.replace(/([^_a-z0-9]+)/g,""),c="",c="SasVideo."+b+" = function(state){",c=c+("var player = SasVideo.getWindowsMedia('"+a.id+"');"),c=c+"player.handleState(state);",c=c+"}";eval(c);this._player.attachEvent("playStateChange",eval("SasVideo."+b));b="wmpposition_"+a.id.replace(/([^_a-z0-9]+)/g,"");c="SasVideo."+b+" = function(oldPosition,newPosition){";
c+="var player = SasVideo.getWindowsMedia('"+a.id+"');";c+="player.handlePosition(oldPosition,newPosition);";c+="}";eval(c);this._player.attachEvent("positionChange",eval("SasVideo."+b))};
SasVideo.WindowsMediaPlayer.prototype.handleState=function(a){if(null!=this._player.controls){var b=parseInt(this._player.controls.currentPosition);1==a?(ob_util.log("WMP media event [stop]"),this.send("stop",b),this._position=0):2==a?(ob_util.log("WMP media event [pause]"),this.send("stop",b),this._position=b):3==a&&(ob_util.log("WMP media event [play]"),this.send("play",this._position))}};
SasVideo.WindowsMediaPlayer.prototype.handlePosition=function(a,b){ob_util.log("WMP media event [positionChange]");this._position=parseInt(b);3==this._player.playState&&(this.send("stop",parseInt(a)),this.send("play",this._position))};
SasVideo.WindowsMediaPlayer.prototype.send=function(a,b){var c=parseInt(this._player.currentMedia.duration);ob_util.log("send ("+this._type+") : "+a+" ("+b+" out of "+c+")");var e=new ob_event("media");e.add("player_id",this._player.id);e.add("media",this._player.fileName);e.add("media_player",this._type);e.add("media_position",b);e.add("media_duration",c);e.add("media_action",a);setTimeout(function(){e.send()},0)};
(function(a){ob_util.MD5=a()})(function(a){var b=function(a,b){return a+b&4294967295},c=function(a,c,e,f,g,m){c=b(b(c,a),b(f,m));return b(c<<g|c>>>32-g,e)},e=function(a,b,e,f,g,m,k){return c(b&e|~b&f,a,b,g,m,k)},f=function(a,b,e,f,g,m,k){return c(b&f|e&~f,a,b,g,m,k)},g=function(a,b,e,f,g,m,k){return c(e^(b|~f),a,b,g,m,k)},k=function(a,q){var h=a[0],l=a[1],n=a[2],m=a[3],h=e(h,l,n,m,q[0],7,-680876936),m=e(m,h,l,n,q[1],12,-389564586),n=e(n,m,h,l,q[2],17,606105819),l=e(l,n,m,h,q[3],22,-1044525330),h=
e(h,l,n,m,q[4],7,-176418897),m=e(m,h,l,n,q[5],12,1200080426),n=e(n,m,h,l,q[6],17,-1473231341),l=e(l,n,m,h,q[7],22,-45705983),h=e(h,l,n,m,q[8],7,1770035416),m=e(m,h,l,n,q[9],12,-1958414417),n=e(n,m,h,l,q[10],17,-42063),l=e(l,n,m,h,q[11],22,-1990404162),h=e(h,l,n,m,q[12],7,1804603682),m=e(m,h,l,n,q[13],12,-40341101),n=e(n,m,h,l,q[14],17,-1502002290),l=e(l,n,m,h,q[15],22,1236535329),h=f(h,l,n,m,q[1],5,-165796510),m=f(m,h,l,n,q[6],9,-1069501632),n=f(n,m,h,l,q[11],14,643717713),l=f(l,n,m,h,q[0],20,-373897302),
h=f(h,l,n,m,q[5],5,-701558691),m=f(m,h,l,n,q[10],9,38016083),n=f(n,m,h,l,q[15],14,-660478335),l=f(l,n,m,h,q[4],20,-405537848),h=f(h,l,n,m,q[9],5,568446438),m=f(m,h,l,n,q[14],9,-1019803690),n=f(n,m,h,l,q[3],14,-187363961),l=f(l,n,m,h,q[8],20,1163531501),h=f(h,l,n,m,q[13],5,-1444681467),m=f(m,h,l,n,q[2],9,-51403784),n=f(n,m,h,l,q[7],14,1735328473),l=f(l,n,m,h,q[12],20,-1926607734),h=c(l^n^m,h,l,q[5],4,-378558),m=c(h^l^n,m,h,q[8],11,-2022574463),n=c(m^h^l,n,m,q[11],16,1839030562),l=c(n^m^h,l,n,q[14],
23,-35309556),h=c(l^n^m,h,l,q[1],4,-1530992060),m=c(h^l^n,m,h,q[4],11,1272893353),n=c(m^h^l,n,m,q[7],16,-155497632),l=c(n^m^h,l,n,q[10],23,-1094730640),h=c(l^n^m,h,l,q[13],4,681279174),m=c(h^l^n,m,h,q[0],11,-358537222),n=c(m^h^l,n,m,q[3],16,-722521979),l=c(n^m^h,l,n,q[6],23,76029189),h=c(l^n^m,h,l,q[9],4,-640364487),m=c(h^l^n,m,h,q[12],11,-421815835),n=c(m^h^l,n,m,q[15],16,530742520),l=c(n^m^h,l,n,q[2],23,-995338651),h=g(h,l,n,m,q[0],6,-198630844),m=g(m,h,l,n,q[7],10,1126891415),n=g(n,m,h,l,q[14],
15,-1416354905),l=g(l,n,m,h,q[5],21,-57434055),h=g(h,l,n,m,q[12],6,1700485571),m=g(m,h,l,n,q[3],10,-1894986606),n=g(n,m,h,l,q[10],15,-1051523),l=g(l,n,m,h,q[1],21,-2054922799),h=g(h,l,n,m,q[8],6,1873313359),m=g(m,h,l,n,q[15],10,-30611744),n=g(n,m,h,l,q[6],15,-1560198380),l=g(l,n,m,h,q[13],21,1309151649),h=g(h,l,n,m,q[4],6,-145523070),m=g(m,h,l,n,q[11],10,-1120210379),n=g(n,m,h,l,q[2],15,718787259),l=g(l,n,m,h,q[9],21,-343485551);a[0]=b(h,a[0]);a[1]=b(l,a[1]);a[2]=b(n,a[2]);a[3]=b(m,a[3])},p=function(a){var b=
[],c;for(c=0;64>c;c+=4)b[c>>2]=a.charCodeAt(c)+(a.charCodeAt(c+1)<<8)+(a.charCodeAt(c+2)<<16)+(a.charCodeAt(c+3)<<24);return b},r=function(a){var b=[],c;for(c=0;64>c;c+=4)b[c>>2]=a[c]+(a[c+1]<<8)+(a[c+2]<<16)+(a[c+3]<<24);return b},s=function(a){var b=a.length,c=[1732584193,-271733879,-1732584194,271733878],e,f,g;for(e=64;e<=b;e+=64)k(c,p(a.substring(e-64,e)));a=a.substring(e-64);f=a.length;g=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];for(e=0;e<f;e+=1)g[e>>2]|=a.charCodeAt(e)<<(e%4<<3);g[e>>2]|=128<<(e%4<<
3);if(55<e){k(c,g);for(e=0;16>e;e+=1)g[e]=0}b=(8*b).toString(16).match(/(.*?)(.{0,8})$/);a=parseInt(b[2],16);b=parseInt(b[1],16)||0;g[14]=a;g[15]=b;k(c,g);return c},x="0123456789abcdef".split(""),u=function(a){var b;for(b=0;b<a.length;b+=1){for(var c=a,e=b,f=a[b],g="",k=void 0,k=0;4>k;k+=1)g+=x[f>>8*k+4&15]+x[f>>8*k&15];c[e]=g}return a.join("")};a=function(){this.reset()};"5d41402abc4b2a76b9719d911017c592"!==u(s("hello"))&&(b=function(a,b){var c=(a&65535)+(b&65535);return(a>>16)+(b>>16)+(c>>16)<<
16|c&65535});a.prototype.append=function(a){/[\u0080-\uFFFF]/.test(a)&&(a=unescape(encodeURIComponent(a)));this.appendBinary(a);return this};a.prototype.appendBinary=function(a){this._buff+=a;this._length+=a.length;a=this._buff.length;var b;for(b=64;b<=a;b+=64)k(this._state,p(this._buff.substring(b-64,b)));this._buff=this._buff.substr(b-64);return this};a.prototype.end=function(a){var b=this._buff,c=b.length,e,f=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];for(e=0;e<c;e+=1)f[e>>2]|=b.charCodeAt(e)<<(e%4<<3);
this._finish(f,c);a=a?this._state:u(this._state);this.reset();return a};a.prototype._finish=function(a,b){var c=b,e;a[c>>2]|=128<<(c%4<<3);if(55<c){k(this._state,a);for(c=0;16>c;c+=1)a[c]=0}e=8*this._length;e=e.toString(16).match(/(.*?)(.{0,8})$/);c=parseInt(e[2],16);e=parseInt(e[1],16)||0;a[14]=c;a[15]=e;k(this._state,a)};a.prototype.reset=function(){this._buff="";this._length=0;this._state=[1732584193,-271733879,-1732584194,271733878];return this};a.prototype.destroy=function(){delete this._state;
delete this._buff;delete this._length};a.hash=function(a,b){/[\u0080-\uFFFF]/.test(a)&&(a=unescape(encodeURIComponent(a)));var c=s(a);return b?c:u(c)};a.hashBinary=function(a,b){var c=s(a);return b?c:u(c)};a.ArrayBuffer=function(){this.reset()};a.ArrayBuffer.prototype.append=function(a){var b=this._concatArrayBuffer(this._buff,a),c=b.length;this._length+=a.byteLength;for(a=64;a<=c;a+=64)k(this._state,r(b.subarray(a-64,a)));this._buff=a-64<c?b.subarray(a-64):new Uint8Array(0);return this};a.ArrayBuffer.prototype.end=
function(a){var b=this._buff,c=b.length,e=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],f;for(f=0;f<c;f+=1)e[f>>2]|=b[f]<<(f%4<<3);this._finish(e,c);a=a?this._state:u(this._state);this.reset();return a};a.ArrayBuffer.prototype._finish=a.prototype._finish;a.ArrayBuffer.prototype.reset=function(){this._buff=new Uint8Array(0);this._length=0;this._state=[1732584193,-271733879,-1732584194,271733878];return this};a.ArrayBuffer.prototype.destroy=a.prototype.destroy;a.ArrayBuffer.prototype._concatArrayBuffer=function(a,
b){var c=a.length,e=new Uint8Array(c+b.byteLength);e.set(a);e.set(new Uint8Array(b),c);return e};a.ArrayBuffer.hash=function(a,b){var c=new Uint8Array(a),e=c.length,f=[1732584193,-271733879,-1732584194,271733878],g,p,s;for(g=64;g<=e;g+=64)k(f,r(c.subarray(g-64,g)));c=g-64<e?c.subarray(g-64):new Uint8Array(0);p=c.length;s=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];for(g=0;g<p;g+=1)s[g>>2]|=c[g]<<(g%4<<3);s[g>>2]|=128<<(g%4<<3);if(55<g){k(f,s);for(g=0;16>g;g+=1)s[g]=0}e=(8*e).toString(16).match(/(.*?)(.{0,8})$/);
c=parseInt(e[2],16);e=parseInt(e[1],16)||0;s[14]=c;s[15]=e;k(f,s);return b?f:u(f)};return a});
(function(a,b){var c=document.domain,e,f=a.getElementsByTagName(b)[0],g=function(c,g,k){return function(){a.getElementById(g)||(e=a.createElement(b),e.src=c,e.type="text/javascript",g&&(e.id=g),k&&(e.onload=function(){ob_util.log(e.id+" completed loading.");k()},e.onreadystatechange=function(){if("loaded"==e.readyState||"complete"==e.readyState)e.onreadystatechange=null,ob_util.log(e.id+" completed loading."),k()}),f.parentNode.insertBefore(e,f))}},k=function(a,b){var c=document.getElementById(a);
return null!=c&&"object"==typeof c.attributes&&"undefined"!=typeof c.attributes.getNamedItem?(c=c.attributes.getNamedItem(b),null!=c?c.value:null):null}("ob-script","a");ob_util.newvid=null==ob_util.ckR("_SI_VID."+k);ob_util.newsid=null==ob_util.ckR("_SI_SID."+k);c=g(function(a,b,c){var e=ob_util.ckR("_SI_VID."+c),e="?vck="+(null!=e?e:"");null!=b&&(e=e+"&"+("domain="+b));a=a+(null!=c?"/"+c:"")+("/"+(new Date).getTime());return a+e}("//ots.sas.com/t/s/b",c,k),"ob-tag-cfg");g("//ots.sas.com/js/sizzle.min.js",
"ob-tag-sizzle",c)()})(document,"script");
